name: frontend_client
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  meta: ^1.16.0
  dio: ^5.8.0+1
  get_it: ^8.0.3
  go_router: ^15.0.0
  flutter_web_plugins:
      sdk: flutter
  url_launcher: ^6.3.1
  material_symbols_icons: ^4.2810.1
  intl: ^0.20.2
  fl_chart: ^1.0.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  dart_format: ^1.4.0
flutter:
  uses-material-design: true
  assets:
    - assets/